server:
  port: 8081

spring:
  application:
    name: catalog-service

  config:
    import: optional:configserver:http://localhost:8888

  data:
    mongodb:
      uri: mongodb://localhost:27017/netflix


