spring:
  application:
    name: serie-service

  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com



logging:
  level:
    org.springframework.security: DEBUG
