server:
  port: 8081

spring:
  data:
    mongodb:
      # uri: mongodb://catalog-db:27018/netflix
      host: catalog-db
      username: catalog
      password: password
      port: 27018
      database: catalog_database

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com


resilience4j:
  circuitbreaker:
    instances:
      series:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        allow-health-indicator-to-fail: false
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      series:
        wait-duration: 1000
        retry-exceptions:
          - feign.FeignException$InternalServerError
        max-attempts: 3

logging:
  level:
    org.springframework.security: DEBUG