server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
#         Lo descomento solo para pruebas directas sin pasar por el gateway
#        - id: movie-service-route
#          uri: lb://movie-service
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: movieService
#                fallbackUri: forward:/fallback/movie
#          predicates:
#            - Path=/movies/**
#        - id: serie-service-route
#          uri: lb://serie-service
#          filters:
#            - name: CircuitBreaker
#              args:
#                name: serieService
#                fallbackUri: forward:/fallback/serie
#          predicates:
#            - Path=/series/**
        - id: catalog-service-route
          uri: lb://catalog-service
          filters:
            - RewritePath=/series, /catalogs/series
            - RewritePath=/movies, /catalogs/movies
#            - name: CircuitBreaker
#              args:
#                name: catalogService
#                fallbackUri: forward:/fallback/catalog
#                statusCodes:
#                  - 500    # Contar estos código como fallidos, sino si el catalog responde con 500 lo contará como exitoso.
#                           # Sin embargo persiste el problema, que en CLOSED también va al fallbackUri
          predicates:
            - Path=/**
      default-filters:
        - OIDCTokenRelay

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: openid,profile,email
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          google:
            issuer-uri: https://accounts.google.com

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 3
        register-health-indicator: true
        allow-health-indicator-to-fail: false
        automatic-transition-from-open-to-half-open-enabled: true
    instances:
      catalogService:
        base-config: default
      serieService:
        base-config: default
      movieService:
        base-config: default
#  retry:
#    configs:
#      default:
#        wait-duration: 1000
#        max-attempts: 3
#    instances:
#      catalogService:
#        base-config: default
#      serieService:
#        base-config: default
#      movieService:
#        base-config: default


logging:
  level:
    root: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
