server:
  port: 8083

spring:
  data:
    mongodb:
      # uri: mongodb://series-db:27017/netflix
      host: series-db
      username: series
      password: password
      port: 27017
      database: series_database

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://accounts.google.com

logging:
  level:
    org.springframework.security: DEBUG
